// Required Practicals — mapped to AQA, Edexcel, OCR specifications
// These are the practicals that APPEAR IN EXAM QUESTIONS every year

export const REQUIRED_PRACTICALS = {

  'GCSE Physics': {
    AQA: [
      {
        id: 'ph1',
        title: 'Specific Heat Capacity',
        topic: 'Energy',
        apparatus: 'Metal block, immersion heater, thermometer, power supply, ammeter, voltmeter, stopwatch, insulation',
        method: [
          'Measure mass of metal block using balance',
          'Insert immersion heater and thermometer into block',
          'Connect ammeter in series, voltmeter in parallel with heater',
          'Record initial temperature',
          'Switch on, record current (A) and voltage (V) every minute',
          'Calculate energy input: E = VIt',
          'Plot temperature vs time graph',
        ],
        keyEquations: ['E = mcΔT', 'E = VIt', 'c = E ÷ (mΔT)'],
        commonExamQs: [
          'Describe how you would measure the specific heat capacity of a metal block',
          'Explain why insulation is used in this experiment',
          'A student finds their value is higher than the accepted value. Suggest why.',
          'Calculate the specific heat capacity given: mass = 1kg, energy = 4200J, temp rise = 5°C',
          'Sketch a temperature-time graph for this experiment. Label key features.',
        ],
        examTips: [
          'Always mention insulation — this is a required mark point',
          'State that you wait until temperature stops rising before recording final temp',
          'Errors: heat loss to surroundings (systematic), parallax in reading thermometer (random)',
          'The value will always be HIGHER than the accepted value due to heat loss',
        ],
        grade9Points: [
          'Explain how to reduce heat loss (lagging, polystyrene, taking readings quickly)',
          'Discuss why the value of c calculated is always an overestimate',
          'Link to energy stores: electrical energy → thermal energy store of block',
        ],
      },
      {
        id: 'ph2',
        title: 'Resistance (I-V Characteristics)',
        topic: 'Electricity',
        apparatus: 'Power supply, rheostat (variable resistor), ammeter, voltmeter, connecting wires, resistor/bulb/diode',
        method: [
          'Set up circuit: component in series with ammeter, voltmeter in parallel',
          'Include variable resistor to control current',
          'Start with minimum voltage (turn rheostat to maximum resistance)',
          'Record current (A) and voltage (V) readings',
          'Increase voltage in steps, repeat readings',
          'Reverse connections for negative values (for diode)',
          'Plot I-V graph',
        ],
        keyEquations: ['V = IR', 'R = V/I'],
        commonExamQs: [
          'Draw a circuit diagram to investigate the I-V characteristics of a filament bulb',
          'Sketch the I-V graph for a filament bulb and explain its shape',
          'How does the resistance of a filament bulb change as temperature increases?',
          'Explain the shape of the I-V graph for a diode',
          'Calculate resistance from an I-V graph at a specific point',
        ],
        examTips: [
          'Filament bulb: curved I-V graph — resistance INCREASES with temperature',
          'Resistor: straight line through origin — constant resistance (Ohmic)',
          'Diode: conducts in one direction only — threshold voltage ~0.7V',
          'Always reverse the battery to get negative values on the graph',
        ],
        grade9Points: [
          'Explain why resistance of filament increases: more vibrations → more collisions with electrons',
          'Calculate resistance at multiple points to show it is not constant for a bulb',
          'Discuss limitations: temperature of surroundings, heating of connecting wires',
        ],
      },
      {
        id: 'ph3',
        title: 'Density of Regular and Irregular Solids',
        topic: 'Particle Model',
        apparatus: 'Balance, ruler/vernier callipers, displacement can, measuring cylinder, water',
        method: [
          'Regular solid: measure dimensions (l × w × h), calculate volume',
          'Measure mass using balance',
          'Calculate density: ρ = m/V',
          'Irregular solid: fill displacement can to spout level',
          'Submerge object, collect displaced water in measuring cylinder',
          'Volume of water displaced = volume of object',
          'Calculate density: ρ = m/V',
        ],
        keyEquations: ['ρ = m/V'],
        commonExamQs: [
          'Describe how to find the density of an irregularly shaped stone',
          'A student measures: mass = 50g, volume = 20cm³. Calculate density in kg/m³',
          'Explain why the displacement method is used for irregular objects',
          'Suggest one source of error in this experiment and how to reduce it',
          'Convert 8000 kg/m³ to g/cm³',
        ],
        examTips: [
          'Always convert units: 1 g/cm³ = 1000 kg/m³',
          'Wait for water to stop dripping before measuring displaced volume',
          'Error: not waiting for object to fully submerge, reading meniscus incorrectly',
          'Repeat measurements and take mean to reduce random errors',
        ],
        grade9Points: [
          'Compare densities to identify unknown materials',
          'Explain floating/sinking in terms of density comparison with fluid',
          'Discuss precision of measuring cylinder vs burette for small volumes',
        ],
      },
      {
        id: 'ph4',
        title: 'Acceleration and Newton\'s Second Law',
        topic: 'Forces & Motion',
        apparatus: 'Trolley, ramp, light gates or ticker timer, hanging masses, pulley, string, balance, ruler',
        method: [
          'Set up trolley on ramp connected to hanging mass via string and pulley',
          'Measure mass of trolley and hanging masses',
          'Release trolley, measure acceleration using light gates',
          'Repeat with different hanging masses (keep trolley mass constant)',
          'Plot acceleration vs force graph',
          'Then vary trolley mass, keep force constant',
          'Plot acceleration vs 1/mass graph',
        ],
        keyEquations: ['F = ma', 'a = F/m'],
        commonExamQs: [
          'Describe an experiment to investigate how acceleration depends on force',
          'A student plots a graph of acceleration against force. Describe what they should see.',
          'Why should the mass of the hanging weight be much less than the trolley mass?',
          'Calculate the acceleration of a 2kg trolley pulled by a 0.5N force',
          'Sketch and explain the force-acceleration graph expected from this experiment',
        ],
        examTips: [
          'Compensate for friction by tilting ramp slightly',
          'Keep total mass constant when varying force (move masses from trolley to hanger)',
          'Light gates give more precise measurements than ticker timer',
          'Graph of a vs F should be straight line through origin',
        ],
        grade9Points: [
          'Explain why hanging mass must be much smaller than trolley mass',
          'Discuss effect of friction on results and how to minimise it',
          'Analyse anomalous results and suggest causes',
        ],
      },
      {
        id: 'ph5',
        title: 'Waves — Speed of Sound / Ripple Tank',
        topic: 'Waves',
        apparatus: 'Ripple tank with lamp, ruler, stopwatch, stroboscope OR two microphones, oscilloscope, signal generator, speaker',
        method: [
          'Ripple tank: adjust frequency of vibrator',
          'Use stroboscope to freeze wave pattern',
          'Measure wavelength directly using ruler',
          'Count waves passing a point in 10 seconds for frequency',
          'Calculate wave speed: v = fλ',
          'Sound: set up two microphones at measured distance',
          'Use oscilloscope to find time delay',
          'Calculate speed: v = d/t',
        ],
        keyEquations: ['v = fλ', 'v = d/t'],
        commonExamQs: [
          'Describe how to measure the speed of sound in air',
          'A student measures wavelength = 3cm, frequency = 10Hz. Calculate wave speed.',
          'Explain how a ripple tank can be used to demonstrate refraction',
          'Why is it better to measure 10 wavelengths rather than just 1?',
          'Describe what happens to wavelength when frequency increases but speed stays constant',
        ],
        examTips: [
          'Measure multiple wavelengths and divide to reduce uncertainty',
          'Speed of sound in air ≈ 340 m/s — know this value',
          'Speed of light ≈ 3 × 10⁸ m/s — know this value',
          'Always state v = fλ and show substitution in calculations',
        ],
        grade9Points: [
          'Discuss sources of uncertainty (reaction time, measuring single wavelength)',
          'Compare wave speed in different media',
          'Explain refraction in terms of change in wave speed',
        ],
      },
      {
        id: 'ph6',
        title: 'Radiation and Absorption',
        topic: 'Energy',
        apparatus: 'Leslie cube filled with hot water, infrared detector/thermometer, ruler, stopwatch',
        method: [
          'Fill Leslie cube with hot water',
          'Place detector at fixed distance from each surface',
          'Record radiation detected from: black matt, white matt, black shiny, silver shiny',
          'Compare readings',
          'Repeat at different distances to investigate inverse square relationship',
        ],
        keyEquations: [],
        commonExamQs: [
          'Describe an experiment to compare emission of radiation from different surfaces',
          'Which surface of a Leslie cube emits most radiation? Explain why.',
          'Explain why a black matt surface is a better emitter than a silver surface',
          'Suggest one control variable in this experiment',
          'Explain how this experiment could be adapted to investigate absorption',
        ],
        examTips: [
          'Black matt: best emitter AND best absorber',
          'Silver/shiny: worst emitter AND worst absorber (best reflector)',
          'Keep distance constant as a control variable',
          'Temperature of water must be the same for each surface comparison',
        ],
        grade9Points: [
          'Link to real-world applications: solar panels, radiators, thermos flasks',
          'Explain in terms of infrared radiation and surface properties',
          'Discuss the difference between emitting and absorbing radiation',
        ],
      },
      {
        id: 'ph7',
        title: 'Light — Reflection and Refraction',
        topic: 'Waves',
        apparatus: 'Ray box, single slit, glass block/mirror, protractor, plain paper, ruler',
        method: [
          'Reflection: place mirror on paper, draw normal at point of incidence',
          'Shine ray at known angle of incidence, mark reflected ray',
          'Measure angle of reflection, compare to angle of incidence',
          'Refraction: place glass block on paper, trace outline',
          'Shine ray at glass block, mark incident and emergent rays',
          'Remove block, draw refracted ray inside block',
          'Measure angles of incidence and refraction at each surface',
        ],
        keyEquations: ['n = sin i / sin r', 'n = c/v'],
        commonExamQs: [
          'Describe an experiment to investigate refraction of light through a glass block',
          'Light hits a glass block at 30° to the normal. Describe what happens.',
          'Calculate the refractive index given angle of incidence = 45°, angle of refraction = 28°',
          'Explain what total internal reflection is and the conditions needed',
          'Draw a ray diagram showing light passing through a rectangular glass block',
        ],
        examTips: [
          'Angles are ALWAYS measured from the normal, not the surface',
          'Light bends TOWARDS normal when entering denser medium',
          'Light bends AWAY from normal when leaving denser medium',
          'TIR only occurs when going from denser to less dense medium AND angle > critical angle',
        ],
        grade9Points: [
          'Calculate critical angle: sin c = 1/n',
          'Applications of TIR: optical fibres, endoscopes, periscopes',
          'Discuss dispersion: different wavelengths refract by different amounts',
        ],
      },
      {
        id: 'ph8',
        title: 'Magnetic Effect of a Current',
        topic: 'Magnetism & Electromagnetism',
        apparatus: 'Plotting compasses, wire, power supply, rheostat, ammeter, iron filings, cardboard',
        method: [
          'Pass wire vertically through horizontal cardboard',
          'Sprinkle iron filings on cardboard',
          'Switch on current, tap cardboard gently',
          'Observe and sketch pattern of field lines',
          'Use plotting compasses to find direction of field',
          'Reverse current, observe change in direction',
          'Vary current and observe effect on field strength',
        ],
        keyEquations: ['F = BIL'],
        commonExamQs: [
          'Describe the magnetic field pattern around a straight current-carrying wire',
          'What happens to the magnetic field when the current is doubled?',
          'Explain how to determine the direction of the magnetic field using the right-hand rule',
          'Describe how an electromagnet can be made stronger',
          'Explain the motor effect using F = BIL',
        ],
        examTips: [
          'Field lines are CIRCLES around the wire, not straight lines',
          'Right-hand rule: thumb = current direction, fingers = field direction',
          'Stronger field: increase current, more coils, add iron core',
          'Motor effect: use Fleming\'s left-hand rule for direction of force',
        ],
        grade9Points: [
          'Distinguish between magnetic field lines and field lines of isolated charges',
          'Explain the difference between a permanent magnet and an electromagnet',
          'Calculate force on a wire: F = BIL and discuss direction using FLHR',
        ],
      },
    ],

    Edexcel: [
      {
        id: 'ph_e1',
        title: 'Investigating Motion (Trolley and Ramp)',
        topic: 'Forces & Motion',
        apparatus: 'Trolley, ramp, light gates, data logger, ruler, masses',
        method: [
          'Set up two light gates at measured distance apart on ramp',
          'Release trolley from rest, record time between gates',
          'Calculate average velocity: v = d/t',
          'Repeat at different heights to vary acceleration',
          'Use data logger to get more precise readings',
        ],
        keyEquations: ['v = d/t', 'v² = u² + 2as', 'a = (v-u)/t'],
        commonExamQs: [
          'Describe how to use light gates to measure the acceleration of a trolley',
          'Explain why a data logger gives more reliable results than a stopwatch',
          'Calculate acceleration from light gate data',
          'Suggest two sources of error in this experiment',
        ],
        examTips: [
          'Light gates measure time more accurately than human reaction time',
          'Increase number of readings and plot a graph for more reliable results',
          'Always state control variables: mass of trolley, same release point',
        ],
        grade9Points: [
          'Discuss how to use v² = u² + 2as to find acceleration from velocity data',
          'Evaluate the experiment: random vs systematic errors',
        ],
      },
    ],
  },

  'GCSE Chemistry': {
    AQA: [
      {
        id: 'ch1',
        title: 'Making Salts (Neutralisation)',
        topic: 'Chemical Changes',
        apparatus: 'Acid, alkali/insoluble base, burette, pipette, conical flask, indicator, evaporating dish, Bunsen burner, filter funnel',
        method: [
          'Method A (soluble base): use titration to find exact volume of acid needed',
          'Pipette known volume of alkali into flask, add indicator',
          'Add acid from burette until indicator changes colour (endpoint)',
          'Repeat without indicator using exact volumes found',
          'Evaporate solution carefully to crystallise salt',
          'Method B (insoluble base/carbonate): add excess solid to acid',
          'Filter to remove excess solid',
          'Evaporate filtrate to get salt crystals',
        ],
        keyEquations: ['acid + base → salt + water', 'acid + carbonate → salt + water + CO₂'],
        commonExamQs: [
          'Describe how to prepare a pure, dry sample of copper sulfate from copper oxide and sulfuric acid',
          'Why is excess copper oxide used in the preparation of copper sulfate?',
          'Describe the colour change at the endpoint of a titration using methyl orange',
          'Explain why the titration is repeated without indicator',
          'Calculate the concentration of an acid given titration results',
        ],
        examTips: [
          'Excess solid used so all acid is used up — then filter to remove excess',
          'Never evaporate to complete dryness — gently heat then leave to crystallise',
          'Titration: read burette from bottom of meniscus',
          'Repeat titration until concordant results (within 0.1 cm³)',
        ],
        grade9Points: [
          'Calculate moles from titration: n = CV (concentration × volume in dm³)',
          'Use mole ratio to find unknown concentration',
          'Explain sources of error: parallax when reading burette, overshoot of endpoint',
        ],
      },
      {
        id: 'ch2',
        title: 'Electrolysis of Aqueous Solutions',
        topic: 'Chemical Changes',
        apparatus: 'Electrolysis cell, graphite electrodes, power supply, ammeter, voltmeter, test tubes, limewater, damp litmus paper',
        method: [
          'Set up electrolysis cell with chosen electrolyte',
          'Connect graphite electrodes to power supply',
          'Collect gases at each electrode using inverted test tubes',
          'Test gases: hydrogen (squeaky pop), oxygen (glowing splint relights), chlorine (bleaches damp litmus)',
          'Observe electrode changes for metal electrolysis',
          'Measure mass of electrode before and after for copper sulfate',
        ],
        keyEquations: [],
        commonExamQs: [
          'Describe the products at each electrode during electrolysis of brine',
          'Explain why copper electrodes are used in the purification of copper',
          'Predict the products of electrolysis of dilute sulfuric acid',
          'Why do the ions need to be free to move for electrolysis to work?',
          'Write half equations for the reactions at each electrode during electrolysis of brine',
        ],
        examTips: [
          'Brine: hydrogen at cathode (-), chlorine at anode (+), sodium hydroxide in solution',
          'Dilute sulfuric acid: hydrogen at cathode, oxygen at anode',
          'Copper sulfate with copper electrodes: copper deposits at cathode, copper dissolves at anode',
          'Cathode = negative electrode (reduction — gain electrons), Anode = positive (oxidation — lose electrons)',
        ],
        grade9Points: [
          'Write and balance half-equations for electrode reactions',
          'Explain why hydrogen is produced rather than sodium at cathode in brine',
          'Calculate mass deposited using Faraday\'s law (Higher only)',
        ],
      },
      {
        id: 'ch3',
        title: 'Investigating Temperature Changes (Calorimetry)',
        topic: 'Energy Changes',
        apparatus: 'Polystyrene cup, thermometer, measuring cylinder, balance, acid, alkali or fuel, spirit lamp',
        method: [
          'Neutralisation: measure volumes of acid and alkali',
          'Record initial temperatures of both solutions',
          'Mix in polystyrene cup, stir and record maximum temperature',
          'Calculate temperature change',
          'Calculate energy: Q = mcΔT (use 4.2 J/g°C for water)',
          'Calculate enthalpy change per mole',
          'Combustion: weigh fuel before and after burning',
          'Heat known mass of water, record temperature rise',
        ],
        keyEquations: ['Q = mcΔT', 'ΔH = -Q/n'],
        commonExamQs: [
          'Describe how to measure the energy change during neutralisation',
          'A student heats 100g of water from 20°C to 45°C. Calculate the energy transferred.',
          'Explain why a polystyrene cup is used rather than a beaker',
          'The calculated value of enthalpy change is less than the accepted value. Explain why.',
          'Describe how to find the energy content of a food sample by combustion',
        ],
        examTips: [
          'Polystyrene cup: reduces heat loss to surroundings (good insulator)',
          'Values always LESS than theoretical because heat is lost to surroundings and equipment',
          'Use 4.2 J/g°C or 4200 J/kg°C for specific heat capacity of water',
          'Always measure temperature before AND after, use maximum temperature reached',
        ],
        grade9Points: [
          'Calculate molar enthalpy change: ΔH = -Q/n in kJ/mol',
          'Explain bond breaking (endothermic) vs bond forming (exothermic)',
          'Suggest improvements: draught shield, lid on cup, repeat and average',
        ],
      },
      {
        id: 'ch4',
        title: 'Rates of Reaction — Effect of Concentration',
        topic: 'Rates of Reaction',
        apparatus: 'Conical flask, marble chips/sodium thiosulfate/hydrogen peroxide, HCl, measuring cylinder, stopwatch, balance, cotton wool, gas syringe or balance',
        method: [
          'Method 1 (mass loss): place flask on balance, add acid to marble chips',
          'Record mass every 30 seconds until no further change',
          'Plot mass vs time graph',
          'Method 2 (gas volume): collect gas in syringe',
          'Record volume every 30 seconds',
          'Method 3 (colour change — thiosulfate): mark X on paper under flask',
          'Mix sodium thiosulfate and HCl, time until X disappears',
          'Repeat with different concentrations',
        ],
        keyEquations: ['Rate = 1/time', 'Rate = change in quantity / time'],
        commonExamQs: [
          'Describe an experiment to investigate how concentration affects the rate of reaction',
          'Sketch a graph showing mass vs time for marble chips in HCl at two different concentrations',
          'Explain in terms of collision theory why increasing concentration increases rate',
          'Calculate the mean rate of reaction from a graph',
          'Why is it better to measure gas volume than mass loss for small reactions?',
        ],
        examTips: [
          'Control variables: temperature, surface area, volume of solution',
          'Steeper initial gradient = faster rate',
          'Same final mass/volume = same amount of product (same reactant amounts)',
          'Collision theory: more particles per unit volume → more frequent collisions → faster rate',
        ],
        grade9Points: [
          'Calculate rate from tangent to curve at a specific time',
          'Explain activation energy and how concentration affects the proportion of successful collisions',
          'Compare methods: advantages/disadvantages of mass loss vs gas syringe vs colour change',
        ],
      },
      {
        id: 'ch5',
        title: 'Chromatography',
        topic: 'Analysis & Atmosphere',
        apparatus: 'Chromatography paper, pencil, ruler, solvent (water or ethanol), beaker, sample inks/dyes',
        method: [
          'Draw pencil baseline 1cm from bottom of paper',
          'Apply small spots of each sample on baseline (pencil label each)',
          'Pour solvent into beaker to just below baseline level',
          'Hang paper so baseline is above solvent level',
          'Allow solvent to travel up paper until near top',
          'Mark solvent front in pencil immediately',
          'Allow to dry, measure Rf values',
          'Rf = distance moved by spot ÷ distance moved by solvent',
        ],
        keyEquations: ['Rf = distance moved by substance / distance moved by solvent'],
        commonExamQs: [
          'Describe how to carry out paper chromatography to identify food dyes',
          'Calculate the Rf value of a substance that moved 4.5cm when the solvent moved 9cm',
          'A chromatogram shows 3 spots for sample A. What does this tell you?',
          'Explain why pencil is used to draw the baseline rather than pen',
          'Why must the baseline be above the solvent level?',
        ],
        examTips: [
          'ALWAYS use pencil for baseline — pen would dissolve in solvent and run up paper',
          'Baseline ABOVE solvent or the sample will dissolve into the solvent, not travel up',
          'Same Rf value in same solvent = same substance',
          'More spots = more components in the mixture',
        ],
        grade9Points: [
          'Compare Rf values to identify unknown substances against known standards',
          'Explain why different substances travel different distances (solubility in solvent vs attraction to paper)',
          'Suggest why a different solvent might give different Rf values for the same substance',
        ],
      },
      {
        id: 'ch6',
        title: 'Preparation of a Pure Dry Sample of an Insoluble Salt',
        topic: 'Chemical Changes',
        apparatus: 'Two soluble salts, beakers, filter funnel, filter paper, spatula, distilled water, evaporating dish',
        method: [
          'Mix solutions of two soluble salts that form an insoluble product',
          'e.g. lead nitrate + potassium iodide → lead iodide (insoluble)',
          'Stir to ensure complete precipitation',
          'Set up filter funnel with filter paper in conical flask',
          'Pour mixture through filter — precipitate stays on paper',
          'Wash precipitate with distilled water to remove soluble impurities',
          'Scrape precipitate onto clean paper and dry in oven or leave in air',
        ],
        keyEquations: ['Ionic equation for precipitation'],
        commonExamQs: [
          'Describe how to prepare a pure, dry sample of barium sulfate',
          'Write an ionic equation for the formation of barium sulfate',
          'Why is the precipitate washed with distilled water?',
          'How do you know when the reaction is complete?',
          'Suggest why excess of one reactant is NOT used in this method',
        ],
        examTips: [
          'Washing removes soluble impurities (unreacted ions)',
          'Use distilled water (not tap water) for washing — tap water contains ions',
          'Do NOT use excess of either reactant — both would contaminate the product',
          'Different from making soluble salts — no filtration of excess solid needed here',
        ],
        grade9Points: [
          'Write balanced ionic equations including state symbols',
          'Explain spectator ions and why they are omitted from ionic equations',
          'Calculate percentage yield from amounts used',
        ],
      },
      {
        id: 'ch7',
        title: 'Flame Tests and Chemical Tests for Ions',
        topic: 'Analysis & Atmosphere',
        apparatus: 'Nichrome wire, Bunsen burner, dilute HCl, samples, test tubes, reagents (NaOH, AgNO₃, BaCl₂)',
        method: [
          'Flame test: clean wire with HCl, dip in sample, hold in flame',
          'Record colour: Li=red, Na=yellow, K=lilac, Ca=orange-red, Cu=blue-green',
          'Carbonate test: add dilute acid, bubble gas through limewater',
          'Halide test: add dilute HNO₃ then AgNO₃ solution',
          'Cl⁻ = white ppt, Br⁻ = cream ppt, I⁻ = yellow ppt',
          'Sulfate test: add dilute HCl then BaCl₂',
          'White precipitate = sulfate present',
          'Hydroxide test: add NaOH solution, observe precipitate colour',
        ],
        keyEquations: [],
        commonExamQs: [
          'Describe how to carry out a flame test and state the colour for sodium',
          'A student adds NaOH to a solution and gets a blue precipitate. What ion is present?',
          'Describe a test for carbonate ions',
          'Explain why the wire is cleaned with HCl before each test',
          'A solution gives a cream precipitate with acidified silver nitrate. Which halide is present?',
        ],
        examTips: [
          'Wire cleaned with HCl to remove previous sample contamination',
          'NaOH precipitate colours: Cu=blue, Fe2+=green, Fe3+=brown/rust, Al/Mg/Ca=white',
          'Limewater turns milky/cloudy = CO₂ present',
          'Acidify before adding AgNO₃ (use HNO₃ not HCl) to prevent false positives',
        ],
        grade9Points: [
          'Write ionic equations for all ion tests',
          'Suggest a systematic method to identify an unknown compound',
          'Explain limitations of flame tests (sodium masks other colours)',
        ],
      },
      {
        id: 'ch8',
        title: 'Temperature Changes and Activation Energy',
        topic: 'Rates of Reaction',
        apparatus: 'Water bath, thermometer, sodium thiosulfate, HCl, conical flask, stopwatch, printed X on paper',
        method: [
          'Place flask of sodium thiosulfate in water bath at set temperature',
          'Allow to equilibrate for 5 minutes',
          'Add measured volume of HCl, start stopwatch immediately',
          'Observe from above — stop timer when X is no longer visible',
          'Record time, calculate rate: rate = 1/time',
          'Repeat at 5 different temperatures (20, 30, 40, 50, 60°C)',
          'Plot rate vs temperature graph',
        ],
        keyEquations: ['Rate = 1/time'],
        commonExamQs: [
          'Describe how to investigate the effect of temperature on rate of reaction',
          'Explain why rate increases with temperature using collision theory',
          'A student finds rate doubles for every 10°C rise. Explain this.',
          'Why is it important to keep concentration and volume constant?',
          'Sketch a rate vs temperature graph and describe its shape',
        ],
        examTips: [
          'Higher temperature: particles have more kinetic energy → more frequent collisions AND more collisions exceed activation energy',
          'Rate = 1/time (inversely proportional)',
          'Control variables: concentration, volume, same observer for colour change',
          'Rate typically doubles for every 10°C increase (at lower temperatures)',
        ],
        grade9Points: [
          'Link activation energy to Maxwell-Boltzmann distribution',
          'Explain how catalysts work by providing alternative pathway with lower activation energy',
          'Evaluate precision: colour change is subjective — suggest using colorimeter instead',
        ],
      },
    ],
  },

  'GCSE Biology': {
    AQA: [
      {
        id: 'bi1',
        title: 'Microscopy — Cell Observation',
        topic: 'Cell Biology',
        apparatus: 'Light microscope, glass slides, cover slips, plant material (onion/celery), methylene blue/iodine stain, tweezers, scalpel, lens tissue',
        method: [
          'Cut thin section of plant material',
          'Place on slide, add a drop of stain (iodine for starch, methylene blue for cells)',
          'Lower cover slip at angle to avoid bubbles',
          'Start with lowest magnification, focus using coarse adjustment',
          'Switch to higher magnification, use fine adjustment only',
          'Draw and label what you observe',
          'Calculate actual size: actual size = image size ÷ magnification',
        ],
        keyEquations: ['Magnification = image size / actual size', 'Actual size = image size / magnification'],
        commonExamQs: [
          'Describe how to prepare a slide of an onion cell',
          'Calculate the actual size of a cell given image size and magnification',
          'Explain why iodine solution is used when observing plant cells',
          'Describe what you would see under a microscope in an onion cell',
          'Why is the cover slip lowered at an angle?',
        ],
        examTips: [
          'Lower cover slip at angle to prevent air bubbles',
          'Always start with LOWEST power objective lens',
          'Only use fine adjustment with high magnification',
          'Onion cells: visible cell wall, vacuole, nucleus (no chloroplasts — storage tissue)',
          'Magnification = eyepiece × objective (e.g. 10× × 40× = 400×)',
        ],
        grade9Points: [
          'Convert between μm, mm, cm for size calculations',
          'Explain why electron microscope is needed for subcellular structures',
          'Compare light vs electron microscope: resolution, magnification, living specimens',
        ],
      },
      {
        id: 'bi2',
        title: 'Osmosis in Plant Tissue',
        topic: 'Cell Biology',
        apparatus: 'Potato/celery, cork borer, ruler, balance, salt solutions (0%, 0.5%, 1%, 1.5%, 2%), distilled water, paper towels',
        method: [
          'Cut potato cylinders of equal length and mass using cork borer',
          'Prepare a range of salt solutions at different concentrations',
          'Place potato cylinders in solutions for 30 minutes',
          'Remove, pat dry with paper towel (do NOT wipe)',
          'Measure and record final length and mass',
          'Calculate % change in mass: (final - initial) / initial × 100',
          'Plot % change in mass vs concentration',
          'Read off isotonic point (where % change = 0)',
        ],
        keyEquations: ['% change = (final mass - initial mass) / initial mass × 100'],
        commonExamQs: [
          'Describe an experiment to investigate osmosis in potato tissue',
          'A potato cylinder changes from 5.0g to 4.6g. Calculate the percentage change in mass.',
          'Explain why percentage change in mass is used rather than actual change',
          'Predict what will happen to a potato cylinder placed in a very concentrated salt solution',
          'What does the isotonic point on the graph represent?',
        ],
        examTips: [
          'Pat dry (do NOT wipe) — wiping removes surface cells affecting mass',
          'Use % change not actual change — allows fair comparison between different sized pieces',
          'Isotonic = solution concentration equals cell sap concentration = no net movement',
          'Negative % change = water lost by osmosis = solution more concentrated than cell sap',
          'Positive % change = water gained = solution less concentrated than cell sap',
        ],
        grade9Points: [
          'Explain osmosis in terms of water potential gradient',
          'Link to plant cell structure: turgor pressure and plasmolysis',
          'Determine water potential of potato tissue from graph (where % change = 0)',
        ],
      },
      {
        id: 'bi3',
        title: 'Enzyme Activity — Effect of Temperature/pH',
        topic: 'Organisation',
        apparatus: 'Amylase, starch solution, iodine solution, buffer solutions, water bath, thermometer, spotting tile, pipette, stopwatch',
        method: [
          'Set up water bath at required temperature',
          'Add amylase and starch to separate tubes, allow to equilibrate',
          'Mix amylase and starch, start timer',
          'Every 30 seconds, place a drop on spotting tile with iodine',
          'Blue-black colour = starch still present',
          'When iodine remains orange/yellow = starch fully digested',
          'Record time for complete digestion',
          'Repeat at different temperatures or pH values',
          'Plot rate (1/time) vs temperature or pH',
        ],
        keyEquations: ['Rate = 1/time'],
        commonExamQs: [
          'Describe an experiment to investigate how pH affects amylase activity',
          'Explain why amylase activity decreases above 60°C',
          'Sketch a graph of enzyme activity vs temperature. Describe and explain its shape.',
          'What is the optimum pH for amylase? Explain what happens above and below this.',
          'A student found no starch present after 2 minutes at 37°C. Calculate the rate.',
        ],
        examTips: [
          'Denatured ≠ killed — enzymes are proteins, not living things',
          'Denaturation: high temperature/extreme pH breaks bonds in active site, changes shape permanently',
          'Optimum temperature for most human enzymes ≈ 37°C',
          'Use buffer solutions to control pH accurately',
          'iodine test: blue-black = starch present, orange/brown = no starch',
        ],
        grade9Points: [
          'Explain lock and key / induced fit models of enzyme action',
          'Distinguish between denaturation and reduced activity (reversible vs irreversible)',
          'Evaluate limitations: subjective colour change → suggest colorimeter as improvement',
        ],
      },
      {
        id: 'bi4',
        title: 'Photosynthesis — Effect of Light Intensity',
        topic: 'Bioenergetics',
        apparatus: 'Aquatic plant (Elodea/Cabomba), beaker, lamp, ruler, stopwatch, sodium hydrogen carbonate solution, syringe',
        method: [
          'Set up plant in beaker of sodium hydrogencarbonate solution (provides CO₂)',
          'Place lamp at measured distance from plant',
          'Count bubbles of oxygen produced per minute (or collect and measure volume)',
          'Move lamp to different distances: 5, 10, 15, 20, 25, 30 cm',
          'Record bubbles per minute at each distance',
          'Repeat 3 times, calculate mean',
          'Plot rate of photosynthesis vs light intensity (or vs 1/d²)',
        ],
        keyEquations: ['Light intensity ∝ 1/d²', '6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂'],
        commonExamQs: [
          'Describe an experiment to investigate the effect of light intensity on photosynthesis',
          'Explain why sodium hydrogen carbonate is added to the water',
          'A student doubles the distance from 10cm to 20cm. What happens to light intensity?',
          'Suggest two variables that must be kept constant in this experiment',
          'Explain why the rate of photosynthesis levels off at high light intensities',
        ],
        examTips: [
          'NaHCO₃ ensures CO₂ is not a limiting factor',
          'Light intensity ∝ 1/d² (inverse square law)',
          'Rate levels off = another factor becomes limiting (CO₂ concentration or temperature)',
          'Count bubbles for 1 minute, repeat 3 times, take mean to reduce uncertainty',
          'Keep temperature constant by surrounding beaker with water (heat sink)',
        ],
        grade9Points: [
          'Apply the inverse square law: double distance = quarter light intensity',
          'Identify and explain limiting factors at different light intensities',
          'Suggest why rate might not increase linearly even before limiting factor is reached',
        ],
      },
      {
        id: 'bi5',
        title: 'Reaction Time',
        topic: 'Homeostasis',
        apparatus: 'Ruler, partner, data table',
        method: [
          'Subject holds hand over edge of table, fingers open',
          'Partner holds 30cm ruler vertically with zero at top of subject\'s thumb',
          'Without warning, partner drops ruler',
          'Subject catches ruler as quickly as possible',
          'Record distance dropped in cm',
          'Use equation or table to convert to reaction time',
          'Repeat 10 times, calculate mean (exclude anomalies)',
          'Test effect of: caffeine, fatigue, distraction etc.',
        ],
        keyEquations: ['d = ½gt²', 't = √(2d/g)'],
        commonExamQs: [
          'Describe how to use a ruler drop test to measure reaction time',
          'A ruler drops 15cm before being caught. Calculate the reaction time.',
          'Suggest two ways to make this experiment more reliable',
          'Explain the reflex arc involved in catching the ruler',
          'Why should the test be repeated multiple times?',
        ],
        examTips: [
          'Take mean of multiple readings to reduce effect of random errors',
          'Exclude anomalous results (anticipation can give very short times)',
          'Typical human reaction time: 0.2–0.3 seconds',
          'Always use the same hand, same partner, same starting position',
        ],
        grade9Points: [
          'Apply t = √(2d/g) to calculate reaction time from distance',
          'Distinguish between conscious response (reaction time) and reflex response',
          'Evaluate reliability: number of repeats, same conditions, controlling anticipation',
        ],
      },
      {
        id: 'bi6',
        title: 'Sampling Techniques — Quadrats and Transects',
        topic: 'Ecology',
        apparatus: 'Quadrat, tape measure, identification key, data recording sheet, metre rule',
        method: [
          'Quadrat sampling: identify area to be sampled',
          'Use random numbers to determine coordinates for quadrat placement',
          'Place quadrat at coordinates, identify and count all species inside',
          'Estimate percentage cover for plants',
          'Repeat at multiple random locations (minimum 10)',
          'Calculate mean number/percentage cover',
          'Transect: stretch tape measure across habitat',
          'Place quadrat at regular intervals along transect',
          'Record species at each point',
        ],
        keyEquations: ['Population size = (M × n) / m (mark-recapture)', 'Mean = total ÷ number of samples'],
        commonExamQs: [
          'Describe how to use quadrats to estimate the population of daisies in a field',
          'Explain why random sampling is important',
          'A 1m² quadrat contains 12 daisies. The field is 500m². Estimate the population.',
          'Describe how a transect could be used to study zonation on a rocky shore',
          'Suggest two sources of error when using quadrats',
        ],
        examTips: [
          'Random sampling: use random number generator for coordinates — removes bias',
          'More quadrats = more reliable estimate',
          'Estimate total population: mean per quadrat × total area',
          'Transect shows how species distribution changes along an environmental gradient',
        ],
        grade9Points: [
          'Apply mark-recapture formula: N = (M × n) / m and state assumptions',
          'Evaluate limitations: species must be equally catchable, marks must not affect survival',
          'Discuss statistical analysis: standard deviation, range as measure of spread',
        ],
      },
    ],
  },

  'GCSE Maths': {
    AQA: [], // Maths has no required practicals — it has functional skills instead
    Edexcel: [],
  },

  'GCSE Combined Science (Physics)': {
    AQA: [], // Combined science shares practicals with Triple — just fewer of them
  },
  'GCSE Combined Science (Chemistry)': { AQA: [] },
  'GCSE Combined Science (Biology)': { AQA: [] },
}

// Map combined to triple practicals (combined science does a subset)
REQUIRED_PRACTICALS['GCSE Combined Science (Physics)'].AQA = [
  REQUIRED_PRACTICALS['GCSE Physics'].AQA.find(p => p.id === 'ph1'), // SHC
  REQUIRED_PRACTICALS['GCSE Physics'].AQA.find(p => p.id === 'ph2'), // I-V
  REQUIRED_PRACTICALS['GCSE Physics'].AQA.find(p => p.id === 'ph3'), // Density
  REQUIRED_PRACTICALS['GCSE Physics'].AQA.find(p => p.id === 'ph5'), // Waves
].filter(Boolean)

REQUIRED_PRACTICALS['GCSE Combined Science (Chemistry)'].AQA = [
  REQUIRED_PRACTICALS['GCSE Chemistry'].AQA.find(p => p.id === 'ch4'), // Rates
  REQUIRED_PRACTICALS['GCSE Chemistry'].AQA.find(p => p.id === 'ch3'), // Calorimetry
  REQUIRED_PRACTICALS['GCSE Chemistry'].AQA.find(p => p.id === 'ch5'), // Chromatography
].filter(Boolean)

REQUIRED_PRACTICALS['GCSE Combined Science (Biology)'].AQA = [
  REQUIRED_PRACTICALS['GCSE Biology'].AQA.find(p => p.id === 'bi1'), // Microscopy
  REQUIRED_PRACTICALS['GCSE Biology'].AQA.find(p => p.id === 'bi2'), // Osmosis
  REQUIRED_PRACTICALS['GCSE Biology'].AQA.find(p => p.id === 'bi3'), // Enzymes
  REQUIRED_PRACTICALS['GCSE Biology'].AQA.find(p => p.id === 'bi4'), // Photosynthesis
].filter(Boolean)
